### ISSUE TITLE
ENHANCEMENT: Create service tokens

### ISSUE THREAD

**Issue by ycabrer** [DopplerHQ/terraform-provider-doppler#12]
Hi,  Thank you so much for this service! I am definitely impressed with it.

Might I suggest the ability to create service tokens with this provider? I would like to be able to create them in terraform in inject them into certain resources.

Regards, 
Zhak

**Comment by anglinb** [comment]
👋  Hey everyone, just wanted to chime in that we could use this as well! This a missing link for us to easily spin up a service using terraform cloud. Happy to provide more context on what we're trying to achieve if that's helpful

**Comment by nmanoogian** [comment]
Thanks for letting us know, @anglinb! We'd be keen to know your use case, if you wouldn't mind sharing.

**Comment by anglinb** [comment]
Hey @nmanoogian! Thanks for following up, happy to share what we're doing!

We have a few services running in k8. These services follow the naming conventions from Doppler. So the `crm` service running `prd` secrets would be `crm-prd.domain.com`. We also use clouldflare tunnels to authenticate internal services and setup dns. So to go from 0 to service deployed securely we really just run one terraform project with inputs of `service` and `cfg` and everything gets spun up. The one missing link is stopping to generate the service token from doppler to pass into the[ doppler kubernetes operator](https://docs.doppler.com/docs/kubernetes-operator). We want to provide "prod" environments for our team to deploy into so we want something like `prd_anglinb` to be my specific secret set which associated `prd_anglinb` so I can safely test changes against an almost prod configuration before merging and making those changes customer facing. We have this all automated except for the service token step. We would to close the loop to make these pre-prod environments fully self-serve and automated.

**Comment by nmanoogian** [comment]
Absolutely! Thank you for sharing that detail; that use case makes a ton of sense. We'll keep you posted here with any updates.

**Comment by kilna-decknroll** [comment]
I'd like to add that I could really use this as well!

**Comment by chrisgoffinet** [comment]
I've been thinking about this, and reviewing the existing code. The API for Service Tokens only implements (`LIST, CREATE, DELETE`).  There is no `GET`, the token is generated on `CREATE` is a one-time operation, unlike secrets that where you can obtain an is versioned.  I don't want to release a PR if the Doppler team is planning an API change where they want to adjust the API to expose tokens similar to secrets. @nmanoogian could you provide any updates there and maybe the teams thoughts?  I can work around this limitation by taking advantage of the secrets API in conjunction with service tokens. I have working code that will actually bootstrap off this concept. 

Generated Service Secret Name:
```
const svcPrefix = "SVC_TOKEN"

func svcTokenSecretName(name string) string {
    return fmt.Sprintf("%s_%s", svcPrefix, name)
}
```

Create Flow:
1.  POST to API to create Service Token
2. Take the result of `key` and create a new secret using `svcTokenSecretName(..)`
3. Set the Terraform Schema `computed`  ->  `svcTokenSecretName(..)`

Read Flow:
1. GET to Secrets API using `svcTokenSecretName(..)`
2. Return the value of this secret which is the generated service token in step (1) of Create Flow.

Delete Flow
1. DELETE to Service Token API (project, config, name)
2. POST to Secret API  for (project, config) with `secrets` including `svcTokenSecretName(..)` set to `null` which will indicate to your API to delete this secret.

**Comment by nmanoogian** [comment]
Hey @chrisgoffinet, thanks for working on this!

My plan was to make the token key a computed value which can only be fetched for created objects (not imported ones). The [provider for AWS IAM access keys](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key) takes a similar approach. The Doppler API doesn't internally store the key -- only a hash which can be used for auth.

I'm planning on doing some prototyping this week and I'll post my findings here.

**Comment by chrisgoffinet** [comment]
> Hey @chrisgoffinet, thanks for working on this!
> 
> My plan was to make the token key a computed value which can only be fetched for created objects (not imported ones). The [provider for AWS IAM access keys](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key) takes a similar approach. The Doppler API doesn't internally store the key -- only a hash which can be used for auth.
> 
> I'm planning on doing some prototyping this week and I'll post my findings here.

The reason why I was avoid that approach was due to:
> `secret` Secret access key. This attribute is not available for imported resources. Note that this will be written to the state file. If you use this, please protect your backend state file judiciously. 

I don't think it's good to be storing secret values into state files

**Comment by chrisgoffinet** [comment]
Unless you were just going to be storing the computed hash in state file, I might of missed that.

**Comment by nmanoogian** [comment]
@chrisgoffinet My plan was to store the actual service token in the Terraform state. I'd certainly mark the key value as `sensitive`.

What are your concerns about storing sensitive data in Terraform state? I can definitely understand the concern if you're using local state (where state is stored in a plain JSON file). However, [Terraform has some recommendations](https://www.terraform.io/language/state/sensitive-data) around storing these kinds of values in Terraform Cloud or an S3 backend.

**Comment by chrisgoffinet** [comment]
@nmanoogian I think my concerns around storing sensitive data inside Terraform rely on a few things:

- having to rely on my backend to properly handle sensitive data (local is a no-brainer but things like encryption at rest come to mind)
-  do i always trust the value in my state file or doppler for latest version? if we were to always check doppler, why store it to begin with?

https://cloud.google.com/security/encryption/default-encryption has an excellent overview about all the layers of security Google attempts to prvide customers with various levels and options.

mistakes can happen, so I am curious about how we would do version conflict if the value is in the state file. (i.e: some person or system updates the value in doppler when it was created in terraform)

I am thinking about moving my companies secret data into Doppler (from free to team), one of the factors for me would be making sure I can rely on all of those levels outlined in the link above were considered and implemented. I would effectively have to make sure my backend (either it be Terraform cloud, AWS, GCP, etc) took all those precautions as well So that is a risk factor as a customer I would have to take into consideration.

**Comment by kilna-decknroll** [comment]
My use case is such that I always trust terraform for storage of secrets in state, but I understand the points being made above. The `sensitive` attribute of values in TF makes it pretty easy to manage.

My own use case is such that any doppler token I create is "for" a another given doppler target project/config/secret for storage. If that relationship were managed via doppler's API, doppler tokens could be readable, terraform-importable (so long as the TF ADDR describes not only the source project's token ID but the related exported-to project/config/secret), and if the token was rotated the receiving target secret could automatically be updated with the new value.  That would be my ideal implementation of this feature, but it seems like it would definitely require tweaks to doppler's internal model/API.

**Comment by nmanoogian** [comment]
@chrisgoffinet OK, I think I understand where you're coming from.

Our current secrets data source and secrets resource both work by mirroring Doppler secrets in Terraform. In order to use our provider securely today, it's definitely a requirement that you first configure a secure Terraform backend. [Terraform's docs touch on this](https://www.terraform.io/language/state/sensitive-data) but security elements like at-rest encryption will depend on the backend you use.

> do i always trust the value in my state file or doppler for latest version? if we were to always check doppler, why store it to begin with?

Could you walk me through this a bit? In the context of service tokens, there is nothing that a user could change in Doppler which would conflict with the service token's representation in state. In the context of Doppler secrets, there is a greater risk of this happening but I think it makes sense to treat projects as either "user managed" or "Terraform managed".

@kilna-decknroll Would you be able to accomplish the same thing by storing the service token key in your Terraform state and then using the `doppler_secret` resource to set the secret to that value in the referencing project?

Your use case for service tokens makes sense but I can also imagine scenarios where one might want to generate a service token and use it directly in another resource. For example, one might configure an EC2 instance, generate a service token, and configure the EC2 instance to use it during runtime.

I'd like to add that we really appreciate all of the feedback from the folks commenting in this issue! It's been exciting to see so much interest around this feature and we're keen on building something that fits your use cases.

**Comment by chrisgoffinet** [comment]
> Could you walk me through this a bit? In the context of service tokens, there is nothing that a user could change in Doppler which would conflict with the service token's representation in state. In the context of Doppler secrets, there is a greater risk of this happening but I think it makes sense to treat projects as either "user managed" or "Terraform managed".

Yes that's true, I think I was just speaking from the secrets perspective since a token can't be changed.

Was the technical decision to store those secrets in the state (with secure backend) to help reduce overhead on the API?

Thanks for the prompt replies, it's been helpful.

**Comment by nmanoogian** [comment]
> Was the technical decision to store those secrets in the state (with secure backend) to help reduce overhead on the API?

What would be the alternative to storing the secrets in state?

**Comment by nmanoogian** [comment]
Hey all! v1.1.0 of the Doppler Terraform provider was just released with support for managing projects, environments, configs, and service tokens! 🎉 

Please let me know if you run into any snags!

**Comment by chrisgoffinet** [comment]
@nmanoogian awesome! Thanks so much.
