### ISSUE TITLE
Project does not come with default environments

### ISSUE THREAD

**Issue by paymog** [DopplerHQ/terraform-provider-doppler#36]
When creating a project using the webapp, it comes preloaded with 3 environments (called `configs` in terraform for some reason...). However, when I make a project with the terraform provider, those environments are not automatically created. Why?

Here's me attempting to make a project and a test secret in the `dev` environment:

```
                     # doppler_project.api-server (api-server) will be created
                     + resource "doppler_project" "api-server" {
                   + id   = (known after apply)
                   + name = "api-server"
                   }
goldsky-infra-dev    # doppler_secret.api-server-secret (api-server-secret) will be created
                     + resource "doppler_secret" "api-server-secret" {
                   + computed = (sensitive value)
                   + config   = "dev"
                   + id       = (known after apply)
                   + name     = "paymahn"
                   + project  = "api-server"
                   + value    = (sensitive value)
```

here's that command erroring out:

```
goldsky-infra-dev  ╷
                   │ Error: Doppler Error: Could not find requested config 'dev'
                   │
                   │   with doppler_secret.api-server-secret (api-server-secret),
                   │   on cdk.tf.json line 1247, in resource.doppler_secret.api-server-secret (api-server-secret):
                   │ 1247:       }
                   │
```

Here's a screenshot from the webapp showing that these three envs are automatically created for projects made with the webapp.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/1986950/211202279-47052699-867d-497e-9730-daa38091e84e.png">

**Comment by nmanoogian** [comment]
Hi @paymog, thanks for reaching out and sorry for the confusion on this!

In Doppler, "environments" are the columns in the project dashboard and "configs" are the rows. For example, you might have the environments "Development", "Staging", and "Production" and `dev`, `stg`, and `prd` are the root configs for their respective environments. Branch configs (e.g. `prd_failover`) are branches off of the root in a given environment.

You are absolutely right -- the Doppler Terraform provider does not automatically create the default environments for a project. This is because the provider has resources for managing environments and configs. If Doppler's backend were to automatically create these resources, you wouldn't be able to manage them in Terraform.

**Comment by paymog** [comment]
Ah gotcha! Makes sense that if these were autogenerated then we wouldn't be able to manage them from terraform.

**Comment by nmanoogian** [comment]
Thanks again for the detailed report!
